/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2026. All rights reserved.
 * This source file is part of the Cangjie project, licensed under Apache-2.0
 * with Runtime Library Exception.
 *
 * See https://cangjie-lang.cn/pages/LICENSE for license information.
 */

func name() {
	  let intRange = 0..5
	  // err node
      let unit_004 = for(number in intRange) {print("${number}") }
      let dd= aaa()
}