test.file.invalid=Target file is invalid, please choose cangjie test file which end with '_test.cj'
package.path.empty=Package path is Empty, please choose package path first.
package.not.exist.cj.path=The 'Package' path not in target cangjie code path.
package.not.exist.main.path=The 'Package' path not in main code path.
package.not.exist.test.path=The 'Package' path not in ohosTest code path.
file.not.exist.cj.path=The 'File' path not in target cangjie code path.
file.path.empty=File path is Empty, please choose file path first.
file.not.exist.main.path=The 'File' path not in main code path.
file.not.exist.ohos.test.path=The 'File' path not in ohosTest code path.
file.not.exist.local.test.path=The 'File' path not in test code path.
class.name.empty=Class name is Empty, please choose class name first.
method.name.empty=Method name is Empty, please choose method name first.
run.target.class.not.found.in.register.file=Target test class was not registered in current package 'list_test.cj' file.
run.target.method.not.found.in.parent.class=Target test method was not found in current test class.