#
# Copyright (c) Huawei Technologies Co., Ltd. 2024-2024. All rights reserved.
#
cangjie.apiVersion=12
cangjie.sdk.window.zip=harmonyos-cangjie-sdk-windows.zip
cangjie.sdk.mac.aarch64.zip=harmonyos-cangjie-sdk-mac-arm.zip
cangjie.sdk.mac.x64.zip=harmonyos-cangjie-sdk-mac.zip