sdk.rootPath=cangjie
sdk.configFile=uni-package.json
sdk.type=cjnative
sdk.buildToolsRootPath=build-tools
sdk.build.cjdeclPath=api/modules/linux_ohos_aarch64_{1}/ohos
sdk.build.ohosMacroPath=api/macro/ohos
sdk.build.linuxArmKitPath=api/lib/linux_ohos_aarch64_{1}/kit
sdk.build.linuxArmOhosPath=api/lib/linux_ohos_aarch64_{1}/ohos
sdk.build.linuxX86KitPath=api/lib/linux_ohos_x86_64_{1}/kit
sdk.build.linuxX86OhosPath=api/lib/linux_ohos_x86_64_{1}/ohos
sdk.compatibility.linuxOhosArmApiMockPath=api/lib/linux_ohos_aarch64_{1}/api_mock
sdk.compatibility.linuxOhosX86ApiMockPath=api/lib/linux_ohos_x86_64_{1}/api_mock
sdk.compatibility.linuxOhosArmWrapperMockPath=api/lib/linux_ohos_aarch64_{1}/c_wrapper_mock
sdk.compatibility.linuxOhosX86WrapperMockPath=api/lib/linux_ohos_x86_64_{1}/c_wrapper_mock
sdk.buildTools.cjcPath={0}/bin/cjc
sdk.buildTools.stdPath={0}/modules/linux_ohos_aarch64_{1}/std
sdk.buildTools.windowsRuntimePath={0}/runtime/lib/windows_x86_64_{1}
sdk.buildTools.macArmRuntimePath={0}/runtime/lib/darwin_aarch64_{1}
sdk.buildTools.macX86RuntimePath={0}/runtime/lib/darwin_x86_64_{1}
sdk.buildTools.linuxOhosArmRuntimePath={0}/runtime/lib/linux_ohos_aarch64_{1}
sdk.buildTools.linuxOhosX86RuntimePath={0}/runtime/lib/linux_ohos_x86_64_{1}
sdk.buildTools.linuxX86RuntimePath={0}/runtime/lib/linux_x86_64_{1}
sdk.buildTools.asanPath={0}/runtime/lib/linux_ohos_aarch64_{1}/asan
sdk.buildTools.thirdPartyLibPath={0}/third_party/llvm/lib
sdk.buildTools.toolsBinPath={0}/tools/bin
sdk.buildTools.toolsDtsParserPath={0}/tools/dtsparser
sdk.buildTools.toolsLibPath={0}/tools/lib