# Copyright (c) Huawei Technologies Co., Ltd. 2020-2022. All rights reserved.

# You can set the 4 log levels of "debug"/"info"/"warn"/"error"/"fatal".
# We will only print the log level you set and higher level logs
log_level=debug
debug_enable=true
info_enable=true
warn_enable=true
error_enable=true