/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2026. All rights reserved.
 * This source file is part of the Cangjie project, licensed under Apache-2.0
 * with Runtime Library Exception.
 *
 * See https://cangjie-lang.cn/pages/LICENSE for license information.
 */

// 缩进值 = 总缩进 - 起始位置在同一行的缩进数
func name(){
    Image(@r(app.media.delete)).width(24).height(24).onClick({
        // tap like this
    }).margin(bottom: 20)
}