/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2026-2026. All rights reserved.
 * This source file is part of the Cangjie project, licensed under Apache-2.0
 * with Runtime Library Exception.
 *
 * See https://cangjie-lang.cn/pages/LICENSE for license information.
 */

package com.huawei.cangjie.debugger.ohos;

import com.huawei.bitfun.utils.CodeCheckByPassUtils;
import com.huawei.deveco.ohos.debugcommon.debugger.NativeDebuggerState;
import com.huawei.deveco.ohos.debugcommon.module.ModuleWrapper;
import com.huawei.deveco.projectmodel.ohos.model.TargetManager;
import com.huawei.deveco.projectmodel.ohos.model.impl.OhosModuleModel;
import com.huawei.deveco.projectmodel.ohos.model.impl.OhosTarget;
import com.huawei.deveco.projectmodel.ohos.v2.ProductV2;

import com.google.common.collect.Sets;

import org.jetbrains.annotations.NotNull;

import java.io.File;
import java.io.FileFilter;
import java.io.IOException;
import java.nio.file.FileVisitResult;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.SimpleFileVisitor;
import java.nio.file.attribute.BasicFileAttributes;
import java.util.Collections;
import java.util.Locale;
import java.util.Set;

/**
 * search related symbol files for debugging
 *
 * @since 2022-12-1
 */
public class SymbolFileSearcher {
    /**
     * device abi
     */
    protected Abi myAbi;

    /**
     * Instantiates a new Symbol file searcher.
     *
     * @param abi abi
     */
    public SymbolFileSearcher(Abi abi) {
        this.myAbi = abi;
    }

    /**
     * add symbol dir
     *
     * @param symDirs symbol dir
     * @param paths path
     * @throws IOException exception
     */
    protected static void addSymbolDirectories(@NotNull Set<File> symDirs, @NotNull Iterable<String> paths)
        throws IOException {
        for (String path : paths) {
            FileFilter symbolFileFilter = (file) -> {
                if (file == null) {
                    return false;
                }
                String fileName = file.getName().toLowerCase(Locale.ENGLISH);
                return file.isFile() && fileName.endsWith("so");
            };

            Files.walkFileTree(Path.of(path), getVisitor(symDirs, symbolFileFilter));
        }
    }

    private static SimpleFileVisitor<Path> getVisitor(@NotNull Set<File> symDirs, FileFilter symbolFileFilter) {
        return new SimpleFileVisitor<>() {
            @Override
            public FileVisitResult preVisitDirectory(Path path, BasicFileAttributes attrs) {
                File dir = path.toFile();
                File[] files = dir.listFiles(symbolFileFilter);
                if (files != null && files.length != 0) {
                    symDirs.add(dir);
                }
                return FileVisitResult.CONTINUE;
            }

            @Override
            public FileVisitResult visitFileFailed(Path file, IOException exc) {
                return FileVisitResult.CONTINUE;
            }
        };
    }

    /**
     * get directory where symbols reside
     *
     * @param debuggerState debug state
     * @return Collection of File
     * @throws IOException exception
     */
    public Set<File> getSymbolsDir(NativeDebuggerState debuggerState) throws IOException {
        final Set<File> symDirs = Sets.newLinkedHashSet();
        if (debuggerState != null) {
            addSymbolDirectories(symDirs, debuggerState.getSymbolDirs());
        }
        for (ModuleWrapper moduleWrapper : debuggerState.getMultiModuleWrapper()) {
            Set<File> localSymbolDirs = getLocalSymbolDirs(debuggerState.getProduct(),
                    TargetManager.getInstance().getCurrentTarget(moduleWrapper.getOhosModule()));
            if (localSymbolDirs != null) {
                symDirs.addAll(localSymbolDirs);
            }
        }
        return symDirs;
    }

    /**
     * get local symbol dir
     *
     * @param product product
     * @param target target
     * @return Collection of File
     */
    protected Set<File> getLocalSymbolDirs(ProductV2 product, OhosTarget target) {
        // Get the symbol directory of the build directory generated by the project
        // build
        Set<File> localSymDirs = Sets.newLinkedHashSet();
        if (target == null) {
            return localSymDirs;
        }
        OhosModuleModel module = target.getBelongModuleModel();
        String modulePath = module.getModulePath();
        if (modulePath == null) {
            throw new IllegalStateException("Failed because path of module is null.(" + module.getModuleName() + ')');
        }
        File symbolDir = CodeCheckByPassUtils.getPath(modulePath, "build", product.getName(), "intermediates", "libs",
            target.getName(), myAbi.toString()).toFile();
        if (symbolDir.exists()) {
            localSymDirs.add(symbolDir);
        }
        File compileLibs = CodeCheckByPassUtils.getPath(modulePath, "build", product.getName(), "intermediates", "libs",
                target.getName(), myAbi.toString(), "compileLibs").toFile();
        if (compileLibs.exists()) {
            localSymDirs.add(compileLibs);
        }
        File ohosLibs = CodeCheckByPassUtils.getPath(modulePath, "build", product.getName(), "intermediates", "libs",
                target.getName(), myAbi.toString(), "ohos").toFile();
        if (ohosLibs.exists()) {
            localSymDirs.add(ohosLibs);
        }
        File runtimeLibs = CodeCheckByPassUtils.getPath(modulePath, "build", product.getName(), "intermediates",
                "stripped_native_libs", target.getName(), myAbi.toString(), "runtime").toFile();
        if (runtimeLibs.exists()) {
            localSymDirs.add(runtimeLibs);
        }
        File cjbinLibs = CodeCheckByPassUtils.getPath(modulePath, "build", product.getName(), "intermediates", "libs",
            target.getName(), myAbi.toString(), "cjbins").toFile();
        if (cjbinLibs.exists() && cjbinLibs.isDirectory()) {
            File[] subDirs = cjbinLibs.listFiles(File::isDirectory);
            if (subDirs != null) {
                Collections.addAll(localSymDirs, subDirs);
            }
        }
        return localSymDirs;
    }

    @Override
    public String toString() {
        return "SymbolFileSearcher{}";
    }
}