/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2026. All rights reserved.
 * This source file is part of the Cangjie project, licensed under Apache-2.0
 * with Runtime Library Exception.
 *
 * See https://cangjie-lang.cn/pages/LICENSE for license information.
 */

class Name{
    var people : int16 = 1222;;
    var apple : String1 = "hello";
}

ffunc getName() {
    var one = Name();
    one..apple = "";
    var price = 1;
    price += s;
}